### ISSUE TITLE
compatibility with apcluster R library

### ISSUE THREAD

**Issue by darked89** [cjneely10/affinityprop#20]
Hello,

I understand that this software is in an early stage of development so the question/request is probably too early to ask.
Nevertheless:

would it be possible to run `affinityprop` in a mode  matching `apcluster`? 
 
The later takes a similarity matrix and from what I understand sets at least the  --preference to a value calculated from the input matrix. 

More importantly: 
the best case scenario would be to run  `affinityprop`  taking advantage of the parallel processing but getting the result identical or "close enough" to the result produces by `apcluster` with the same input file. 

At the moment  `affinityprop` run:
```
 affinityprop  --threads 12    --max_iter 1000  --input similarity_matrix_3000.with_rownums.tsv
```

outputs 1108 clusters whereas `apcluster` 349. 

The `similarity_matrix_3000.with_rownums.tsv` contains 2918 x 2918 matrix with negative Euclidean distances with 0s on the diagonal. I have numbered the rows 1-2918 to provide the required identifiers. 

Many thanks for providing another implementation of the affinity clustering.

Darek Kedra

**Comment by cjneely10** [comment]
Hi @darked89,

Thank you for reaching out. Accepting a pre-calculated similarity matrix from the command-line is definitely a useful enhancement - I will add it.

**Comment by cjneely10** [comment]
Hi @darked89,

Running `affinityprop` on a pre-computed similarity matrix is now supported:

1. Update your `affinityprop` installation (you may need to remove your prior installation first):

```
cargo uninstall affinityprop
cargo install affinityprop --git https://github.com/cjneely10/affinityprop --version 0.1.1
```

2. Run the analysis with `-s 3` to use a pre-computed similarity matrix (see the README for more info, including how output is structured). For example:

```
 affinityprop -s 3 -t 12 -c 400 -m 4000 --input similarity_matrix_3000.with_rownums.tsv
```

Feel free to let me know if there are any issues!

**Comment by darked89** [comment]
Dear Christopher,

Very impressive response time! 

I can confirm that it does work. 
```(sh)
affinityprop -s 3 -t 16 -c 400 -m 4000 --input similarity_matrix_3000.tsv
```
execution took 28s on Ryzen 7 5800X. 

There is a one minor issue. When run with ```similarity_matrix_3000.with_rownums.tsv``` I got:

```
Precalculated input data must be square!
```
Tried a common-sense column & row names, but then 2919 rows and 2918 columns gave me the same error. I can live with it and add the experiments names downstream, but for the easier usage I would suggest some extra flag (--labels / --labeled-matrix or something like that). 

I will get back to you about number of clusters later during the day.

Many thanks.

Darek Kedra

**Comment by cjneely10** [comment]
Hi Darek,

Another great idea! I updated the software to include a `--no_labels` flag for files that do not include a column of row ids (more info on the README). Thank you for the enhancement ideas for this program, let me know if there are any issues. 

Currently, this implementation gathers F1 scores between 0.98-1.00 when compared to an existing Python sklearn version, so I am curious to see how it performs when compared to the R implementation.

**Comment by darked89** [comment]
Hi Christopher,

Sorry for the delay. I can confirm that everything works as expected with the ```--no_labels``` flag. As for the cluster similarity I will open a separate issue(s) to keep the topics ordered. 

Best,

DK
