### ISSUE TITLE
descriptive parsing error messages

### ISSUE THREAD

**Issue by darked89** [cjneely10/affinityprop#41]
**problem**
Some input file may contain NA values at some row/column deep down the file. At the moment the program reports i.e.:

```
Error parsing file at line 1125
```

IMHO this is a bit cryptic, and since my first idea was that during the pre-processing leading to the input file somehow I got one column too many/or missing on some rows. 

**proposed solution**
1. print out if possible some info about what was the error:
* wrong number of columns?
* offending value: "NA"  

Thanks a lot for your help,

Darek Kedra

**Comment by cjneely10** [comment]
Hi @darked89,

Thank you for posting this issue - the current error logging is definitely lacking.

I have linked a PR that should handle this far better.

Best,

Chris
